# Generated by Django 5.0.6 on 2024-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('supervizor', 'Supervisor'), ('mentor', 'Mentor'), ('shop', 'Shop'), ('security', 'Security'), ('office', 'Office'), ('support', 'Support')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField()),
                ('message_kz', models.TextField()),
                ('message_ru', models.TextField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
