# Generated by Django 5.0.6 on 2024-07-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='day',
            field=models.IntegerField(verbose_name='Дни'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('mentor', 'Mentor'), ('shop', 'Shop'), ('security', 'Security'), ('office', 'Office'), ('support', 'Support')], max_length=20),
        ),
    ]
