# Generated by Django 5.0.6 on 2024-07-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['id'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
    ]
